//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTarget.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceItem()
        {
            this.CloseItem = new HashSet<CloseItem>();
        }
    
        public int IdServiceItem { get; set; }
        public string NameServiceItem { get; set; }
        public System.DateTime StartSate { get; set; }
        public System.DateTime FinishDate { get; set; }
        public int Coun { get; set; }
        public double Price { get; set; }
        public double Total { get; set; }
        public int IdSpecification { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CloseItem> CloseItem { get; set; }
        public virtual Specification Specification { get; set; }
        public override string ToString()
        {
            return NameServiceItem.ToString();
        }
    }
}
